src/Entity/Property.php
<?php
//Ce fichier est l'entité property qui contient des methodes avec les informations sur les champs de notre base de données
//On a les getter et setter qui sont des methodes qui vont effectuer des actions sur les les champs

//Repertoire de travail
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType ;

//Cette annotation associe l'entité au repository qui lui va faire le pont entre l'entité et la base de données
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{

    const STATUT = [
        0 => 'à faire',
        1 => 'en cours',
        2 => 'terminé'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetimetz")
     */
    private $date;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default":0})
     */
    private $statut;

    public function __construct()
{
    $this->date = new \DateTime('now');
    
}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(int $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getStatutType(): string 
    {
        return self::STATUT[$this->statut];
    }

}

src/Form/Property2Type.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Property2Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description')
            
            ->add('statut', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }

    private function getChoices() 
    {
        $choices = Property::STATUT;
        $output = [];
        foreach($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class HomeController
{
    /**
     * @var Environment
     */

    private $twig;

    public function __construct($twig)
    {
        $this->twig = $twig;
    }


    /**
     * @param PropertyRepository $repository
     * @return Response
     */
    public function index(PropertyRepository $repository): Response
    {
        $properties = $repository->findAll();
        return new Response($this->twig->render('Taches/home.html.twig', [
            'properties' => $properties    
        ]));
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\Property2Type;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/property")
 */
class PropertyController extends AbstractController
{
    //methode qui va recupérer toutes les données dans la base et les afficher
    //on a la route aussi en annotation
    /**
     * @Route("/", name="property_index", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('property/index.html.twig', [
            'properties' => $propertyRepository->findAll(),
        ]);
    }

    //methode qui va créer une nouvelle tache

    /**
     * @Route("/new", name="property_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $property = new Property();
       
        $form = $this->createForm(Property2Type::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);//on met en fil d'attente les modifications 
            $entityManager->flush();//on apporte les modification à la base de données

            return $this->redirectToRoute('property_index');//on redirige l'utilisateur sur la page de listing des taches
        }

        return $this->render('property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    //methode qui affiche une tache spécifique avec toutes ses informations

    /**
     * @Route("/{id}", name="property_show", methods={"GET"})
     */
    public function show(Property $property): Response
    {
        return $this->render('property/show.html.twig', [
            'property' => $property,
        ]);
    }

    //methode qui va permettre d'éditer une tache et apporter de ce fait des modifications

    /**
     * @Route("/{id}/edit", name="property_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Property $property): Response
    {
        $form = $this->createForm(Property2Type::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) //on vérifie après soumission si le formulaire est valide 
        {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('property_index');//après l'édition on redirige l'utilisateur sur la page de listing  
        }

        return $this->render('property/edit.html.twig', [
            'property' => $property,
            'form' => $form->createView(),//on envoie à la vue
        ]);
    }

    //methode qui va supprimer les taches

    /**
     * @Route("/{id}", name="property_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Property $property): Response
    {
        //on verifie que le token est valide avant de supprimer pour accroitre la sécurité
        if ($this->isCsrfTokenValid('delete'.$property->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($property);//on supprime la tache 
            $entityManager->flush();//qui va apporter grace à doctrine les modifications effectué à la base de données
        }

        return $this->redirectToRoute('property_index');
    }
    
}

templates/Taches/home.html.twig
{% extends 'base.html.twig' %}

{% block title 'Application Symfony'%}

{% block body %}
<h1 style="text-align:center">Bienvenue sur mon application Symfony</h1>

<div class="container">
    <h2>Les dernières taches</h2>
    <div class="row flex">
        {% for property in properties %}
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{ path('property_show', {id: property.id}) }}">{{ property.titre }}</a>
                        </h5>
                        <p class="card-text">{{ property.date|date('Y-m-d H:i:s') }}</p>
                        <p class="card-text">{{ property.description }}</p>
                        <div class="text-primary">{{ property.statutType }}</div>
                    </div>
                </div>
            </div>

             {% else %}
                    
                <div class= "alert alert-secondary" role= "alert"> Pas de Tâches </div>
            
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Mon application Symfony!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ path('home') }}">Tâches</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{ path('property_new') }}">Créer des tâches</a>
                    <a class="nav-item nav-link" href="{{ path('property_index') }}">Modifier les tâches</a>
                </div>
            </div>
        </nav>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

templates/property/_delete_form.html.twig
<form method="post" action="{{ path('property_delete', {'id': property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
    <button class="btn">Delete</button>
</form>

templates/property/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/property/edit.html.twig
{% extends 'base.html.twig' %}

{% block title 'Editer les taches' %}

{% block body %}
    <div class="container mt-4">
        <h1>Editer les taches</h1>
        {{ form_start(form) }}
            {{ form_rest(form) }}
            <button class="btn btn-primary">Editer</button>
            <a href="{{ path('property_index') }}" class="btn btn-secondary">Retour</a>
        {{ form_end(form) }}
        
    </div
{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier les tâches{% endblock %}

{% block body %}

    <div class="container mt-4">
    <h1 style="text-align:center">Modifier les tâches</h1>
        <h1>Tableau de bord</h1>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Statut</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
        

        <tbody>
                {% for property in properties %}
                    <tr>
                        <td>{{ property.titre }}</td>
                        <td>{{ property.statutType }}</td>
                        <td>{{ property.description }}</td>
                        <td>
                            <a href="{{ path('property_edit', {'id': property.id}) }}" class="btn btn-primary">Editer</a>
                            <form method="post" action="{{ path('property_delete', {'id': property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" style="display:inline-block">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
                                <button class="btn btn-danger">Supprimer</button>
                            </form>

                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <div class= "alert alert-secondary" role= "alert" colspan="6"> Pas de Tâches </div>
                    </tr>
        
                {% endfor %}
            </tbody>
        </table>
        <div class="text-right">
            <a href="{{ path('property_new') }}" class="btn btn-primary">Créer une nouvelle tache</a>
        </div>
    </div>
{% endblock %}


       

templates/property/new.html.twig
{% extends 'base.html.twig' %}

{% block title 'Créer une tache' %}

{% block body %}
    <div class="container mt-4">
        <h1>Créer une taches</h1>
        {{ form_start(form) }}
            {{ form_rest(form) }}
            <button class="btn btn-primary">Créer</button>
            <a href="{{ path('property_index') }}" class="btn btn-secondary">Retour</a>
        {{ form_end(form) }}

    </div
    
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Editer la tâche' %}

{% block body %}
    <div class="container mt-4">
         <table class="table">
        <tbody>
        
            <tr>
                <th>Titre</th>
                <td>{{ property.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ property.description }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ property.date ? property.date|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ property.statutType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('property_index') }}" class="btn btn-secondary">Retour</a>

    <a href="{{ path('property_edit', {'id': property.id}) }}" class="btn btn-primary">Editer</a>

    <form method="post" action="{{ path('property_delete', {'id': property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" style="display:inline-block">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
        <button class="btn btn-danger">Supprimer</button>
    </form>
    </div
{% endblock %}

   